version: "3"
services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --incremental --verbose --livereload --livereload-port 4001
    ports:
      - 4000:4000
      - 4001:4001
    volumes:
      - .:/srv/jekyll
